#!/bin/bash
#
# 'Make SFZ' by RockHopper 2013
#
# This is a Nautilus script to invoke makesfz. It assumes that makesfz is installed
# in a directory included in the PATH environment variable (e.g. /usr/bin, /usr/local/bin) 
# and that xterm is available.
#
# This script is public domain and provided 'as-is', without any express or implied 
# warranty. In no event will the author be held liable for any damages arising from 
# the use of this software.


# These variables may be modified if you need to specify the file path of makesfz
# or if you wish to use a different terminal emulator

MAKESFZ_PATH="makesfz"
TERMINAL_COMMAND="xterm -hold -title MakeSFZ -font 9x15 -e"
# TERMINAL_COMMAND="konsole --hold -e"

# N.B. For a list of available fonts in xterm type: appres XTerm | grep VT100.font
##################################################################################


declare -a filePaths

while IFS="\n" read -r -d $'\n' filePath; do
    filePaths+=("$filePath")
done < <(echo -n "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")

$TERMINAL_COMMAND "$MAKESFZ_PATH" -I -- "${filePaths[@]}"

