#!/bin/bash
#
# 'Make SFZ' by Andrew M Taylor 2013
#
# This is a Nautilus script to invoke makesfz. It assumes that makesfz is installed
# in a directory included in the PATH environment variable (e.g. /usr/bin, /usr/local/bin) 
# and that xterm is available.
#
# This is free and unencumbered software released into the public domain.
# Please read UNLICENSE for more details, or refer to <http://unlicense.org/>


# These variables may be modified if you need to specify the file path of makesfz
# or if you wish to use a different terminal emulator

MAKESFZ_PATH="makesfz"
TERMINAL_COMMAND="xterm -bg black -hold -title MakeSFZ -font 9x15 -e"
# TERMINAL_COMMAND="konsole --hold -e"

# N.B. For a list of available fonts in xterm type: appres XTerm | grep VT100.font
##################################################################################


declare -a filePaths

while IFS="\n" read -r -d $'\n' filePath; do
    filePaths+=("$filePath")
done < <(echo -n "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS")

$TERMINAL_COMMAND "$MAKESFZ_PATH" -I -- "${filePaths[@]}"

